# run the test suite
tests:
    image: registry.gitlab.lis-lab.fr:5005/baptiste.bauvin/summit/ubuntu:18.04
    tags:
        - docker
    script:
        - pip3 install -e . --no-deps
        - pytest-3
    coverage: '/^TOTAL.+?(\d+\%)$/'
    artifacts:
        paths:
            - htmlcov/

# generate the documentation
doc:
    image: registry.gitlab.lis-lab.fr:5005/baptiste.bauvin/summit/ubuntu:18.04
    tags:
        - docker
    only:
        - master
        - develop
    script:
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install -e .[doc]
        - sphinx-apidoc -o docs/source summit
        - cd docs/source
        - sphinx-build -b html . ../build
        - cd ../..
        - cp -r ./docs/build public
    artifacts:
        paths:
            - public
            - htmlcov

# project public
pages:
    image: registry.gitlab.lis-lab.fr:5005/baptiste.bauvin/summit/ubuntu:18.04
    tags:
        - docker
    only:
        - master
    script:
        - export LC_ALL=$(locale -a | grep en_US)
        - export LANG=$(locale -a | grep en_US)
        - pip3 install -e .[doc]
        - pytest-3
        - sphinx-apidoc -o docs/source summit
        - cd docs/source
        - sphinx-build -b html . ../build
        - cd ../..
        - cp -r ./docs/build public
        - mkdir public/coverage
        - mv htmlcov/index.html public/coverage/
        - mv htmlcov/style.css public/coverage/
    artifacts:
       paths:
            - public

