# The base configuration of the benchmark
log: True
name: ["ionosphere"]
label: "_"
file_type: ".hdf5"
views:
pathf: "/home/baptiste/Documents/Datasets/UCI/both"
nice: 0
random_state: 42
nb_cores: 1
full: False
debug: True
add_noise: False
noise_std: 0.0
res_dir: "../results/"
track_tracebacks: False

# All the classification-realted configuration options
multiclass_method: "oneVersusOne"
split: 0.75
nb_folds: 5
nb_class: 2
classes:
type: ["monoview"]
algos_monoview: ["scm_bagging",]
algos_multiview: ["group_scm"]
stats_iter: 2
metrics:
  accuracy_score: {}
  f1_score:
    average: 'binary'
metric_princ: "f1_score"
hps_type: "Random"
hps_args: {}