# The base configuration of the benchmark
log: True
name: ["digits"]
label: "_"
file_type: ".hdf5"
views:
pathf: "/home/baptiste/Documents/Datasets/Digits/"
nice: 0
random_state: 42
nb_cores: 1
full: True
debug: True
add_noise: False
noise_std: 0.0
res_dir: "../results/"
track_tracebacks: False

# All the classification-realted configuration options
multiclass_method: "oneVersusOne"
split: 0.25
nb_folds: 5
nb_class:
classes:
type: ["multiview", "monoview"]
algos_monoview: ["cb_boost","decision_tree", "random_forest"]
algos_multiview: ["mumbo","mvml", "lp_norm_mkl", "mucombo"]
stats_iter: 10
metrics: ["accuracy_score", "f1_score"]
metric_princ: "accuracy_score"
hps_type: "randomized_search-equiv"
hps_iter: 5