# The base configuration of the benchmark
Base :
  log: True
  name: ["plausible"]
  label: "_"
  type: ".hdf5"
  views:
  pathf: "../data/"
  nice: 0
  random_state: 42
  nb_cores: 1
  full: True
  debug: True
  add_noise: False
  noise_std: 0.0
  res_dir: "../results/"

# All the classification-realted configuration options
Classification:
  multiclass_method: "oneVersusOne"
  split: 0.2
  nb_folds: 2
  nb_class: 2
  classes:
  type: ["multiview",]
  algos_monoview: ["all"]
  algos_multiview: ["mvml",]
  stats_iter: 2
  metrics: ["accuracy_score", "f1_score"]
  metric_princ: "f1_score"
  hps_type: "randomized_search"
  hps_iter: 1