# The base configuration of the benchmark
log: True
name: ["mnist_0_9_train"]
label: "_"
file_type: ".hdf5"
views: ["NIMST_data", ]
pathf: "/home/baptiste/Documents/Datasets/MNist/"
nice: 0
random_state: 43
nb_cores: 1
full: False
debug: True
add_noise: False
noise_std: 0.0
res_dir: "../results/"
track_tracebacks: False

# All the classification-realted configuration options
multiclass_method: "oneVersusOne"
split: 0.96
nb_folds: 5
nb_class: 2
classes:
type: ["monoview",]
algos_monoview: ["hm_gb_cbound","cb_boost"]
algos_multiview: ["mumbo","mvml"]
stats_iter: 1
metrics:
  zero_one_loss: {}
  f1_score: {}
metric_princ: "zero_one_loss"
hps_type: "None"
hps_args:
  n_iter: 2