# The base configuration of the benchmark
log: True
name: ["generated_dset"]
label: "_"
file_type: ".hdf5"
views:
pathf: "/home/baptiste/Documents/Gitwork/multiview_generator/generator/"
nice: 0
random_state: 42
nb_cores: 1
full: True
debug: True
add_noise: False
noise_std: 0.0
res_dir: "../results/"
track_tracebacks: False

# All the classification-realted configuration options
split: 0.5
nb_folds: 5
nb_class:
classes:
type: ["monoview", "multiview",]
algos_monoview: ["decision_tree",]
algos_multiview: ["mumbo","weighted_linear_early_fusion"]
stats_iter: 30
metrics: ["accuracy_score", "f1_score"]
metric_princ: "accuracy_score"
hps_type: "None"
hps_args:
  n_iter: 4
  equivalent_draws: False

  decision_tree:
    max_depth: 3


  weighted_linear_early_fusion:
    view_weights: null
    monoview_classifier: "decision_tree"
    monoview_classifier__max_depth: 10

  mumbo:
    n_estimators: 15
    decision_tree:
      max_depth: 3