# The base configuration of the benchmark
log: True
name: ["plausible"]
label: "_"
file_type: ".hdf5"
views:
pathf: "../data/"
nice: 0
random_state: 42
nb_cores: 1
full: True
debug: True
add_noise: False
noise_std: 0.0
res_dir: "../results/"
track_tracebacks: True

# All the classification-realted configuration options
multiclass_method: "oneVersusOne"
split: 0.5
nb_folds: 2
nb_class: 2
classes:
type: ["multiview"]
algos_monoview: ["cb_boost"]
algos_multiview: ["mucombo", "mumbo", "lp_norm_mkl", "mvml"]
stats_iter: 1
metrics: ["accuracy_score", "f1_score"]
metric_princ: "f1_score"
hps_type: "randomized_search"
hps_iter: 2